version: '3.6'

services:
  # app:
  #     build: .
  #     ports:
  #       - 8080:8080
  #     image: app
  #     environment:
  #       OWA_CLIENT_ID: b77e07f479efe92156376a8b07640ced
  #       OWA_URL: http://api.openweathermap.org/data/2.5/weather?
  #       SPOTIFY_CLIENT_ID: BQBA-mqrxN8Bjm3W4KhfxKb4SOREHZWS-_R416dcKTdq0_VrwV1dBk3Xp35e42texThTey35KZnZW0n_nma17xxzm-h6Sk2jsO9THxBN_BjumfTFWJjJWboMvI7BQ5lK5IvJWYLnRopp
  #       SPOTIFY_URL: https://api.spotify.com/v1/recommendations?
  #       REDIS_ADDRESS: redis:6379
  #       REDIS_PASS: ""
  #       GIN_MODE: release
  #     networks:
  #       - app_public

  redis:
    image: redis
    container_name: redis
    ports: 
      - 6379:6379
    networks:
      - app_public

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./resources/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app_public
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: "grafana"
    ports:
      - 3000:3000
    networks:
      - app_public
    volumes:
      - ./resources/grafana:/var/lib/grafana

networks:
  app_public:
    name: app_public
